version: '3.1'

services:
  postgres:
    ports:
      - 5432:5432
    build: ./db
    restart: 'always'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cmyk
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: