// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as ApolloLinks from "reason-apollo/src/ApolloLinks.bs.js";
import * as ReasonApollo from "reason-apollo/src/ReasonApollo.bs.js";
import * as ApolloInMemoryCache from "reason-apollo/src/ApolloInMemoryCache.bs.js";

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* None */0, /* None */0, /* () */0);

var httpLink = ApolloLinks.createHttpLink("https://localhost:3000/graphql", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var instance = ReasonApollo.createApolloClient(httpLink, inMemoryCache, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

export {
  inMemoryCache ,
  httpLink ,
  instance ,
  
}
/* inMemoryCache Not a pure module */
