// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function CreateContext(C) {
  var context = React.createContext(C[/* value */1]);
  var make = function (value, children) {
    return ReasonReact.wrapJsForReason(context["Provider"], {
                value: value
              }, children);
  };
  var Provider = /* module */[/* make */make];
  var make$1 = function (children) {
    return ReasonReact.wrapJsForReason(context["Consumer"], { }, children);
  };
  var Consumer = /* module */[/* make */make$1];
  return /* module */[
          /* context */context,
          /* Provider */Provider,
          /* Consumer */Consumer
        ];
}

export {
  CreateContext ,
  
}
/* react Not a pure module */
