// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Css from "bs-css/src/Css.js";
import * as Client from "./Client.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as ApolloProvider from "reason-apollo/src/ApolloProvider.bs.js";

Css.$$global("html", /* :: */[
      Css.padding(Css.rem(0)),
      /* :: */[
        Css.margin(Css.rem(0)),
        /* :: */[
          Css.fontFamily("sans-serif"),
          /* [] */0
        ]
      ]
    ]);

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client.instance, /* array */[ReasonReact.element(/* None */0, /* None */0, App.make(/* array */[]))])), "app");

export {
  
}
/*  Not a pure module */
