// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Context from "./Context.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function initialState() {
  return /* record */[/* route */ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0)];
}

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

function subscriptions(param) {
  var send = param[/* send */3];
  return /* :: */[
          /* Sub */[
            (function () {
                return ReasonReact.Router[/* watchUrl */1]((function (route) {
                              return Curry._1(send, /* ChangeRoute */[route]);
                            }));
              }),
            ReasonReact.Router[/* unwatchUrl */2]
          ],
          /* [] */0
        ];
}

var value = /* record */[/* route */ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0)];

var ContextConfig = /* module */[
  /* debugName */"RouterContext",
  /* value */value
];

var RouterContext = Context.CreateContext(ContextConfig);

var component = ReasonReact.reducerComponent("Router");

function make(children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return ReasonReact.element(/* None */0, /* None */0, Curry._2(RouterContext[/* Provider */1][/* make */0], param[/* state */1], /* array */[children]));
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */subscriptions,
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  initialState ,
  reducer ,
  subscriptions ,
  ContextConfig ,
  RouterContext ,
  component ,
  make ,
  
}
/* value Not a pure module */
